### ISSUE TITLE
Include KMZ support

### ISSUE THREAD

**Issue by diVineProportion** [Vyrtuoz/Tacview#2]
Since KMZ is simply compressed KML, maybe add support?

**Comment by BuzyBee1983** [comment]
For static objects or flight recording?

**Comment by diVineProportion** [comment]
Both? Just to be clear, we are only speaking in terms of import right? I was looking over the acmi documentation to get a feel for everything made available to me to make use of and came across KML files. When grabbing some stuff off the internet (believe it was a marked airport locations i.e. static objects) I noticed that some were KMZ instead of KML, and that tacview couldn't import the KMZ until I had decompressed it to KML. This is less of a 'something does't work' and more of a 'could this make tacview better'

**Comment by diVineProportion** [comment]
as txt.acmi files are to zip.acmi files,
kml files are to kmz files

simply is a compressed version. KML's are usually distributed across the net as compressed KMZ files, so since tacview can uncompress zip/zip.acmi, was thinking it could do this same for kmz. Right now tacview can open kml but not the compressed kmz

sorry if it was confusing earlier

**Comment by RaiaSoftwareInc** [comment]
Hi, this is on our to-do list! It is taking longer than expected because it is a different data flow which does not pass by the zip unpacker.

**Comment by diVineProportion** [comment]
ahh, apologies as I assumed this was standard zip. I was only suggesting to try to make tacview better, not that I needed this feature hahah.. so put it to the back of the list lol!

**Comment by Vyrtuoz** [comment]
You are right, KMZ are zip archives. It is just that the module which manage static objects in Tacview does not know how to load multiple kml files recursively. That’s why this feature require more programming than it seems.
